language: java

jdk:
 - openjdk8
 - openjdk11
 - openjdk12

sudo: required

services:
  - docker

before_script:
  - chmod +x gradlew
  
script:
  - java -version
  - ./gradlew check --parallel
  - ./gradlew codeCoverageReport

notifications:
  email:
    on_success: change
    on_failure: always

after_success:
 - bash <(curl -s https://codecov.io/bash)

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
